### PR TITLE
Add support for setting server_name as query parameter

### PR DESCRIPTION
**Pull request by johanfleury**
Implements #74

### CODE REVIEW

**Comment by ribbybibby** [comment]
The same proposal has been rejected in the blackbox_exporter: https://github.com/prometheus/blackbox_exporter/issues/624.

I'm sympathetic to the reasoning there that this issue can be solved by configuration management.

**Comment by k0ste** [comment]
I agree that this possible to cover cases like this via IaC, in per-module manner. We do it like [this](https://github.com/k0ste/ansible-role-ssl_exporter/blob/main/README.md?plain=1#L32-L35) with `ssl_exporter` Ansible role

**Comment by johanfleury** [comment]
I’m closing the PR as I’m not using ssl_exporter that way anymore since I left my previous company.

I still think that having to manage a configuration file is a pain, especially when you already have everything you need in the service discovery labels.

Of course everything is always possible (depending on the time you’re willing to put into it), but managing the configuration dynamically in the Kubernetes context (in which this issue arose) is not the simplest thing to do.

**Comment by LDaneliukas** [comment]
@ribbybibby seeing as blackbox_exporter now accepts [hostname as a parameter,](https://github.com/prometheus/blackbox_exporter/pull/823) can this be re-opened?

**Pull request closed without merging**
